name: game
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.15.0-268.8.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  #Audio Player
  audioplayers: ^0.20.1

  #Firebase
  cloud_firestore: ^3.1.0
  firebase: ^9.0.2
  firebase_core: ^1.10.0

  flutter:
    sdk: flutter

  #State Management
  flutter_mobx: ^2.0.2
  mobx: ^2.0.5
  mobx_codegen: ^2.0.4

  #Responsive Design
  flutter_screenutil: ^5.0.1

  fluttertoast: ^8.0.8
  device_preview: ^1.0.0

  #Cache Management
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.7

  #Api Business
  http: ^0.13.4

  #Utilities
  intl: ^0.17.0
  kartal: ^2.2.0
  lottie: ^1.2.1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/sounds/
